language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE testmaster;' -U postgres
notifications:
  email: false
deploy:
  api_key:
    secure: Cp3yk5LQ7tOBGjNi9OjBlVKnA5Lypw/yEh+q3i6IJxBDAqkt2SkatRuLUENehlVu/YygzEF37t6MslY+wTXd8yrGqCeog6l/0P5wggHOVOHCMP66R4mXrGXRTGmSNW9Uj8A8Ai1qFIiH3tsdJk2zRKIN63hNEsajTL2fPT40K2qfc6ee45Mhvl4djjKVPshkSMXXsyJSgUkGIljFu+waQOoo+SFvNQQF5kTN2VE7Pvda8pHqmG82AWe9PLCdxYv7Et6O3lfjtT38n9uGxu3ojVLC6WLZA1uOqolReG/vUOusWnAgk0iVwfOhpV3l7B8X3uLSvUd9/IyBsysWwSNxYi4Tv4plhfNC8IvWtHlQxf0P30hFJxq7FtI9nwsfI3X95MFd+bnaA1zqm18Ax1N5bDZtOuZ86SVhrM5T0pVcJUbn5Uqtox/QeLQv7VoQeyPVwzSGz91hxqfcczTAXZucxpeynaL8WDoeAsChs1uI7RtSFA5Ft9qm0rQnnnIXhfoMi4EwEL3lLgDlGgg0ZWVNhdXRAWjxGPLomN0CL481a9DDzJe4gnXXYy4342dNVYOzCpK8nPdVf4eWBPojKlMMi9ORl4gbaVkx85yPWXM7nlyScIGRGB78LnLOMNos1PisgZaBZLkJbnJT+6LHSEpYsUmCVgzvSOGwEqOeHxphyqU=
